{% set name = "osqp" %}
{% set version = "0.4.0" %}
{% set osqp_version = version %}
{% set qdldl_version = "0.1.2" %}  # Keep this up to date too! :/

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/oxfordcontrol/osqp-python/archive/v{{ version }}.tar.gz
    fn: osqp-python-{{ version }}.tar.gz
    sha256: 6d7721a33bc00a005430f255348150433b1f4637b1519b2d4f2bb4fb8e4bf530
  - url: https://github.com/oxfordcontrol/osqp/archive/v{{ osqp_version }}.tar.gz
    fn: osqp-{{ version }}.tar.gz
    sha256: aaf3c5553590b10eafd8214e681a218f128fb88cf5ae84b78d8b3a571dc868aa
    folder: osqp_sources
  - url: https://github.com/oxfordcontrol/qdldl/archive/v{{ qdldl_version }}.tar.gz
    fn: qdldl-{{ qdldl_version }}.tar.gz
    sha256: e059b02516a5314e2a1d69c9ede910ef3a532699c76d5455a53dbff8a97f1fe5
    folder: osqp_sources/lin_sys/direct/qdldl/qdldl_sources

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # figure out Windows build later...  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.2
    - future

test:
  imports:
    - osqp
    - osqp.codegen
    - osqppurepy
  requires:
    - pytest
  commands:
    # codegen interface requires compiler + cmake
    # want to make sure other stuff works without it...
    - python -m pytest --pyargs osqp -k 'not codegen_'

about:
  home: https://osqp.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python interface for OSQP, the Operator Splitting QP Solver'
  description: |
    Python interface for OSQP, the Operator Splitting QP Solver.

    To use the `codegen` interface, install `cmake` and an appropriate
    compiler version. (We don't install this by default.)
  doc_url: https://osqp.org/
  dev_url: http://github.com/oxfordcontrol/osqp-python

extra:
  recipe-maintainers:
    - dougalsutherland
