{% set version = "1.0.3" %}
{% set lib_version = "1.0.0" %}

package:
  name: osqp
  version: {{ version }}

source:
  url: https://github.com/osqp/osqp-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f50db86014085255230d93419c2cbd2ec468fa4d01aee8f3b441fb2d04322407
  patches:
    - patches/0001-Link-against-shared-osqp-library.patch
    - patches/0002-disable-codegen-ABI-is-not-compatible.patch

build:
  number: 0
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}  # [unix]
    - set "SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}"   # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pybind11
  host:
    - python
    - scikit-build-core
    - setuptools_scm
    - pip
    - numpy
    - libosqp {{ lib_version }}
    - setuptools
  run:
    - python
    - qdldl-python
    - jinja2
    - joblib
    - scipy
  run_constrained:
    # since paradiso directly depends on the SO name, which was changed then
    - mkl >=2022.0                   # [win]

test:
  imports:
    - osqp
    - osqp.codegen
  requires:
    # some of the tests need mkl-specific solvers
    - blas=*=mkl                     # [x86_64]
    - pytest
    - pytorch
  commands:
    # codegen tests are disabled because they require an incompatible ABI, see patches
    {% set tests_to_skip = "codegen" %}
    # skip tests that takes 90%+ of test suite runtime (and is xfailed anyway)
    {% set tests_to_skip = tests_to_skip + " or test_multithread" %}  # [aarch64 or ppc64le]
    - python -m pytest --pyargs osqp -k "not ({{ tests_to_skip }})"

about:
  home: https://osqp.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python interface for OSQP, the Operator Splitting QP Solver'
  description: |
    Python interface for OSQP, the Operator Splitting QP Solver.

    To use the `codegen` interface, install `cmake` and an appropriate
    compiler version. (We don't install this by default.)
  doc_url: https://osqp.org/
  dev_url: http://github.com/osqp/osqp-python

extra:
  recipe-maintainers:
    - sebp
    - djsutherland
    - h-vetinari
    - bstellato
    - gbanjac
    - jayfurmanek
