appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: EUMb4rnwL7CAigPFiomCQlxX3F+Bivx+1JprUzbYV9bvrOQAedo0xwKsUqmpMBVqCYiI4uKYA7fsR5O6oJ6/lO7+bFdeo0zztB0d/G5oZJfZ72szur7+U/j9jlEwB4BmMFzCc+vkWsf/uk93up72WJU/xKQAutXEqfVkW2lJ9ug2hasH0A2su7Lbx498Aqnlu/PjCwA3VxToYDT4L5tdga2Vs6qfiwPbaYsZPWiUybojRA0Quq18ty4rnijzfxQPEz3QhkPwlfEFCtdoe5CjOaK+Hwx+lHBoXijtnEEjkRRcvBeirKdDrAMUUZp74Zv5Z7U2CLRFlW622qm24Nx3+WdD68itT4JQACwubyscfXrFmYWfL92Pyd9SlDsKY9o/OvCFnoDppHRxsIRuqkc4U2xq2aW/xwrdukEXncOGybxgamCSeWFq+fTO94CvkgNhRG6cIQ9Y77MdMcahsYnRr/2gE/Qsh9LvqETi+RkBS+/xuGXyKtfu84fMlL51uZHyA+4p0NDcoqBKLc9ykox+5Y/7IfFpyqRgD2I+naIUQYNaNPkpmXE/ET4pGlx33fVUk9DbsWvm2uI0xLvLdINZbaESUrhZ+zRN7ZNr70XjiuiURIQePjFSqpLEU/rEagNRA/ScmLuaRqaTlOKKyzU/yNMNq69nTszFWKZUCGwa/i8=}
